Models/Instructor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContosoUniversity.Models
{
    public class Instructor : Person
    {
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Hire Date")]
        public DateTime HireDate { get; set; }

        public ICollection<CourseAssignment> CourseAssignments { get; set; }
        public OfficeAssignment OfficeAssignment { get; set; }
    }
}

Controllers/InstructorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

using ContosoUniversity.Data;
using ContosoUniversity.Models;
using ContosoUniversity.Models.ViewModels;

namespace cu_pum.Controllers
{
    public class InstructorController : Controller
    {
        private readonly SchoolContext _context;

        private readonly ILogger<InstructorController> _logger;

        public InstructorController(SchoolContext context, ILoggerFactory loggerFactory)
        {
            _context = context;
            _logger = loggerFactory.CreateLogger<InstructorController>();
        }

        // GET: Instructor
        public async Task<IActionResult> Index()
        {
            var InstructorsList = await _context.Instructor
                        .Include(instr => instr.CourseAssignments)
                        .ThenInclude(ca => ca.Course)
                        .Include(instr => instr.OfficeAssignment)
                        .ToListAsync();
            return View(InstructorsList);
        }
      

        // GET: Instructor/Details/5
        public async Task<IActionResult> Details(int? id, int? CourseID)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instructor = await _context.Instructor
                .Include(instr => instr.CourseAssignments)
                .ThenInclude(ca => ca.Course)
                .Include(instr => instr.OfficeAssignment)
                .FirstOrDefaultAsync(m => m.ID == id);           

            if (instructor != null)
            {
                // TODO: extract
                IEnumerable<Enrollment> ex = null;
                if (CourseID != null)
                {
                    var courseAssigment = instructor.CourseAssignments.Where(x => x.CourseID == CourseID).Single(); 
                    var selectedCourse = courseAssigment.Course;
                    ViewData["Course"] = selectedCourse.Title;
                    await _context.Entry(selectedCourse).Collection(x => x.Enrollments).LoadAsync();
                    foreach (Enrollment enrollment in selectedCourse.Enrollments)
                    {
                        await _context.Entry(enrollment).Reference(x => x.Student).LoadAsync();
                    }
                    ex = selectedCourse.Enrollments;
                }
                var details = new InstructorDetailsData() {
                    Instructor = instructor,
                    Enrollments = ex
                };
                return View(details);
            }
            return NotFound();            
        }

        // GET: Instructor/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Instructor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HireDate,ID,LastName,FirstMidName")] Instructor instructor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(instructor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(instructor);
        }

        // GET: Instructor/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                var instructor = await _context.Instructor
                    .Include(instr => instr.CourseAssignments)
                    .ThenInclude(ca => ca.Course)
                    .Include(instr => instr.OfficeAssignment)
                    .FirstOrDefaultAsync(m => m.ID == id);
                    
                if (instructor != null)
                {
                    _logger.LogDebug($"Requets for {id}");
                    var editInstructor = new InstructorEditForm() {
                        ID = instructor.ID,
                        FirstMidName = instructor.FirstMidName,
                        LastName = instructor.LastName,
                        HireDate = instructor.HireDate
                    };
                    if (instructor.OfficeAssignment != null)
                    {
                        editInstructor.Office = instructor.OfficeAssignment?.Location;
                    }
                    else
                    {
                        editInstructor.Office = "";
                    }
                     
                    editInstructor.Courses = _context.getCoursesMap(instructor.ID);
                    _logger.LogDebug($"Answer is {editInstructor}");
                    return View(editInstructor);   
                }
            }
            return NotFound();
        }

        // POST: Instructor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, 
                                                [Bind("ID,HireDate,LastName,FirstMidName,Office,selectedCourses")] 
                                                InstructorEditResponse response)
        {
            if (id == response.ID)
            {
                if (ModelState.IsValid)
                {
                    try
                    {                    
                        var instructor = new Instructor() {
                            ID = response.ID,
                            FirstMidName = response.FirstMidName,
                            LastName = response.LastName,
                            HireDate = response.HireDate
                        };
                        _context.Update(instructor);
                        
                        var officeAssignment = new OfficeAssignment() {
                            InstructorID = response.ID,
                            Location = response.Office
                        };                        
                        if (!_context.AnyOfficeAssignmentExists(officeAssignment))
                        {
                            _logger.LogDebug($"New office assigment for {officeAssignment.Location}");
                            _context.Add(officeAssignment); 
                        }
                        else
                        {
                            _logger.LogDebug($"Updating of office assigment for {officeAssignment.Location}");
                            _context.Update(officeAssignment);
                        }
                        // TODO: extract Course Assigment
                        if (response.selectedCourses != null)
                        {
                            var _instructor = await _context.Instructor
                                                .Include(instr => instr.CourseAssignments)
                                                .ThenInclude(ca => ca.Course)
                                                .FirstOrDefaultAsync(m => m.ID == id);
                            if (_instructor != null)
                            {
                                var allCourses = await _context.Courses.ToListAsync();
                                var assignedCourses = _instructor.CourseAssignments.ToList();
                                var updatedCourses = new List<int>(response.selectedCourses);
                                // stage 1: remove assigment
                                foreach (var course in assignedCourses)
                                {
                                    if (!updatedCourses.Contains(course.CourseID))
                                    {
                                        var x = allCourses.Find(c => c.CourseID == course.CourseID);
                                        if (x != null)
                                        {
                                            _context.CourseAssignments.Remove(course);                                            
                                        }
                                        updatedCourses.Remove(course.CourseID);                                   
                                    } 
                                }
                                // stage 2: add assigment
                                foreach (var newCourse in updatedCourses)
                                {
                                    if (!_context.CourseAssignmentExists(newCourse, response.ID))
                                    {   
                                        _context.Add(new CourseAssignment() 
                                                    { 
                                                        CourseID = newCourse, 
                                                        InstructorID = response.ID
                                                    });
                                    }
                                }
                                await _context.SaveChangesAsync();                               
                            }                            
                        }
                        await _context.SaveChangesAsync();                                                 
                    }
                    catch (DbUpdateConcurrencyException)
                    {

Views/Instructor/Create.cshtml
@model ContosoUniversity.Models.Instructor

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Instructor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstMidName" class="control-label"></label>
                <input asp-for="FirstMidName" class="form-control" />
                <span asp-validation-for="FirstMidName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

Views/Instructor/Delete.cshtml
@model ContosoUniversity.Models.Instructor

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Instructor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HireDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstMidName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

Views/Instructor/Details.cshtml
@model ContosoUniversity.Models.ViewModels.InstructorDetailsData

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>Instructor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Instructor.FirstMidName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Instructor.FirstMidName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Instructor.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Instructor.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Instructor.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Instructor.HireDate)
        </dd>
        <dt class = "col-sm-2">
            Office
        </dt>
        <dd class = "col-sm-10">
            @if (Model.Instructor.OfficeAssignment != null)
            {
                @Html.DisplayFor(model => model.Instructor.OfficeAssignment.Location)
            }
        </dd> 
        <dt class = "col-sm-2">
            Course(s)
        </dt>
        <dd class = "col-sm-10">
            @if (Model.Instructor.CourseAssignments != null)
            {
                @foreach (var ca in Model.Instructor.CourseAssignments)
                { 
                    <p>                   
                    @Html.ActionLink(@ca.Course.Title, "Details", "Instructor", new { Id = @Model.Instructor.ID, CourseID = @ca.Course.CourseID})
                    </p>
                }                                                
            }
        </dd>       
    </dl>
</div>
@if (Model.Enrollments != null)
{
    <h5>
        Students Enrolled in Course '@ViewBag.Course'
    </h5>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Grade</th>
        </tr>
        @foreach (var item in Model.Enrollments)
        {
            <tr>
                <td>
                    @item.Student.FullName
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grade)
                </td>
            </tr>
        }
    </table>
}
<div>
    <a asp-action="Edit" asp-route-id="@Model.Instructor.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

Views/Instructor/Edit.cshtml
@model ContosoUniversity.Models.ViewModels.InstructorEditForm

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Instructor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="FirstMidName" class="control-label"></label>
                <input asp-for="FirstMidName" class="form-control" />
                <span asp-validation-for="FirstMidName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Office" class="control-label">Office</label>
                <input asp-for="Office" class="form-control" />
                <span asp-validation-for="Office" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Courses" class="control-label">Course(s)</label>
                <table>                   
                    @if (Model.Courses != null)
                    {
                        <thead>
                            <tr>
                                <th>Assign</th>
                                <th>Title</th>                                
                            </tr>
                        </thead>                        
                        @foreach (var course in Model.Courses)
                        {
                            var selOption = "";
                            @if (course.Assigned)
                            {
                                selOption = "checked";
                            }
                            <tr>
                                <td><input type="checkbox"
                                               name="selectedCourses"
                                               value="@course.CourseID"
                                               @selOption/>
                                </td>
                                <td>@course.Title</td>                                
                            </tr>                            
                        }
                    }
                </table>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

Views/Instructor/Index.cshtml
@model IEnumerable<ContosoUniversity.Models.Instructor>

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                <!--@Html.DisplayNameFor(model => model.CourseAssignments)-->
                Course(s)
            </th>            
            <th>
                Office
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                <!--@Html.DisplayFor(modelItem => item.HireDate)-->
                
                    @if (item.CourseAssignments != null)
                    {
                        @if (item.CourseAssignments.Count >= 1)
                        {                            
                            @foreach (var c in item.CourseAssignments)
                            {
                                <p>@c.Course.Title</p>
                            }                            
                        }
                        else 
                        {
                            @:<p>no assigned course</p>
                        }                       
                    }               
                                
            </td>
            <td>
                @if (item.OfficeAssignment != null)
                {
                    @item.OfficeAssignment.Location
                }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</body>
</html>